// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyNnOtZ5M_ZtGO77HdCqr3hw4Kjjiju0Y',
    appId: '1:385532474090:web:da2ebd65914e412926dd93',
    messagingSenderId: '385532474090',
    projectId: 'e-shop-836cc',
    authDomain: 'e-shop-836cc.firebaseapp.com',
    storageBucket: 'e-shop-836cc.firebasestorage.app',
    measurementId: 'G-RJ4J2C7QTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKyjwZEWg16HlSj_pWp4drZ2g2ZIJrKec',
    appId: '1:385532474090:android:011737539992316926dd93',
    messagingSenderId: '385532474090',
    projectId: 'e-shop-836cc',
    storageBucket: 'e-shop-836cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA88cLTJTfLmW9TDPUp4xHUbFtPnCOVXmE',
    appId: '1:385532474090:ios:3a90faec5776f25926dd93',
    messagingSenderId: '385532474090',
    projectId: 'e-shop-836cc',
    storageBucket: 'e-shop-836cc.firebasestorage.app',
    iosBundleId: 'com.example.eShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA88cLTJTfLmW9TDPUp4xHUbFtPnCOVXmE',
    appId: '1:385532474090:ios:3a90faec5776f25926dd93',
    messagingSenderId: '385532474090',
    projectId: 'e-shop-836cc',
    storageBucket: 'e-shop-836cc.firebasestorage.app',
    iosBundleId: 'com.example.eShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyNnOtZ5M_ZtGO77HdCqr3hw4Kjjiju0Y',
    appId: '1:385532474090:web:4980bb8554c82dc326dd93',
    messagingSenderId: '385532474090',
    projectId: 'e-shop-836cc',
    authDomain: 'e-shop-836cc.firebaseapp.com',
    storageBucket: 'e-shop-836cc.firebasestorage.app',
    measurementId: 'G-SDDYG7RC5J',
  );
}
